import type { Metadata } from "next";
import { Lexend, Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header/Header";

const lora = Lora({
  variable: "--lora",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${lexend.variable} antialiased`}>
        <Header />
        <div className="size-full flex pt-[calc(64px+2*20px)]">{children}</div>
      </body>
    </html>
  );
}
