import type { Metadata } from "next";
import { Lexend, Lora } from "next/font/google";
import "./globals.css";

const lora = Lora({
  variable: "--lora",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const lexend = Lexend({
  variable: "--lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "Lyna | %s",
    default: "Lyna",
  },
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${lexend.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
