import { InformationPage } from "@/components/ui/InformationPage";
import { InformationSection } from "@/components/ui/InformationSection";
import { InformationTitle } from "@/components/ui/InformationTitle";
import TextBold from "@/components/ui/TextBold";
import { LastUpdated } from "@/components/ui/lastUpdate";
import { Paragraph } from "@/components/ui/paragraph";

const TermsOfUse = () => {
  return (
    <InformationPage>
      <LastUpdated date="January 1, 2026" />
      <InformationTitle>Terms of Use</InformationTitle>
      <InformationSection
        title="1. Introduction and Acceptance"
        className="mt-8"
      >
        <Paragraph>
          These Terms of Use ({`"Terms"`}) form a legally binding agreement
          between you ({`"you"`} or {`"User"`}) and LYNA CAM UK Limited (
          {`"LYNA,"`} {`"we,"`}
          {`"us,"`} or {`"our"`}). They govern your access to and use of our
          website, mobile application, and related services (collectively, the
          {`"Service"`}).
          <br />
          <br />
          By accessing or using the Service, you agree to these Terms, as well
          as our Privacy Policy and Cookie Policy. If you do not agree, you must
          not access or use the Service.
        </Paragraph>
      </InformationSection>
      <InformationSection title="2. Definitions" className="mt-20">
        <Paragraph indent={"sm"}>
          <TextBold>• Service:</TextBold> LYNA’s website, mobile application,
          and all associated features and services.
          <br />
          <TextBold>• User Content:</TextBold> Any data, images, text, audio,
          video, or other content submitted, uploaded, or generated by you
          through the Service.
          <br />
          <TextBold>• Personal Information:</TextBold> Information relating to
          an identifiable individual, as defined under applicable data
          protection laws.
        </Paragraph>
      </InformationSection>
      <InformationSection title="3. Eligibility" className="mt-20">
        <Paragraph>
          You must be at least <TextBold>13 years old</TextBold> (or the minimum
          legal age in your jurisdiction) to use the Service. If you are under
          18, you confirm that you have obtained permission from a parent or
          legal guardian to use the Service.
        </Paragraph>
      </InformationSection>
      <InformationSection
        title="4. Account Registration and Security"
        className="mt-20"
      >
        <Paragraph>
          When creating an account, you agree to provide accurate, complete, and
          up-to-date information. You are responsible for all activity that
          occurs under your account and for maintaining the confidentiality of
          your login credentials. You must notify us immediately at{" "}
          <TextBold>hello@lyna.com</TextBold> if you suspect any unauthorized
          use of your account or security breach.
        </Paragraph>
      </InformationSection>
      <InformationSection title="5. Limited License" className="mt-20">
        <Paragraph>
          Subject to your compliance with these Terms, LYNA grants you a
          limited, non-exclusive, non-transferable, revocable license to access
          and use the Service for personal, non-commercial purposes only. All
          rights not expressly granted are reserved by LYNA.
        </Paragraph>
      </InformationSection>
      <InformationSection title="6. Acceptable Use" className="mt-20">
        <Paragraph>You agree not to:</Paragraph>
        <Paragraph indent={"sm"}>
          • Violate any applicable laws, regulations, or third-party rights.
          <br />
          • Upload, post, or transmit content that is unlawful, harmful,
          abusive, harassing, defamatory, or otherwise objectionable.
          <br />
          • Attempt to gain unauthorized access to the Service, user accounts,
          or systems.
          <br />
          • Reverse engineer, decompile, scrape, or otherwise attempt to extract
          source code or data from the Service.
          <br />• Use the Service in any way that could damage, disable,
          overburden, or impair LYNA or harm other users.
        </Paragraph>
      </InformationSection>
      <InformationSection title="7. User Content" className="mt-20">
        <Paragraph>
          You retain ownership of your User Content. By submitting User Content,
          you grant LYNA a limited, non-exclusive, royalty-free, worldwide
          license to host, store, use, reproduce, and display such content
          solely for the purpose of operating, maintaining, and improving the
          Service.
          <br />
          <br />
          You are solely responsible for your User Content and for ensuring it
          complies with these Terms and all applicable laws.
        </Paragraph>
      </InformationSection>
      <InformationSection title="8. Health and AI Disclaimer" className="mt-20">
        <Paragraph>
          LYNA is provided for{" "}
          <TextBold>informational and wellness purposes only</TextBold> and does
          not constitute medical, diagnostic, or treatment advice. Any insights
          or outputs generated by the Service, including those using artificial
          intelligence, are probabilistic in nature and may be inaccurate or
          incomplete.
          <br />
          <br />
          You should always consult a qualified healthcare professional before
          making health-related decisions.
        </Paragraph>
      </InformationSection>
      <InformationSection
        title="9. Payments and Subscriptions"
        className="mt-20"
      >
        <Paragraph>
          Certain features of the Service may require payment. Prices, billing
          terms, renewal conditions, and cancellation policies will be disclosed
          at the point of purchase.
          <br />
          <br />
          All payments are processed securely via third-party payment providers.
          Fees are non-refundable except where required by applicable law.
        </Paragraph>
      </InformationSection>
      <InformationSection title="10. Intellectual Property" className="mt-20">
        <Paragraph>
          All content, software, trademarks, and materials provided by LYNA
          (excluding User Content) are owned by or licensed to LYNA and are
          protected by intellectual property laws.
          <br />
          <br />
          You may not copy, modify, distribute, sell, or create derivative works
          from any LYNA content without our prior written consent.
        </Paragraph>
      </InformationSection>
      <InformationSection title="11. Privacy" className="mt-20">
        <Paragraph>
          Your use of the Service is governed by our Privacy Policy and Cookie
          Policy, which describe how we collect, use, and protect your personal
          data in accordance with UK data protection laws.
        </Paragraph>
      </InformationSection>
      <InformationSection title="12. Third-Party Services" className="mt-20">
        <Paragraph>
          The Service may include links to or integrations with third-party
          websites, content, or services. LYNA does not control and is not
          responsible for these third parties or their practices. Your use of
          third-party services is at your own risk and subject to their terms.
        </Paragraph>
      </InformationSection>
      <InformationSection title="13. Termination" className="mt-20">
        <Paragraph>
          We may suspend or terminate your access to the Service at any time,
          with or without notice, if we reasonably believe you have violated
          these Terms or pose a risk to LYNA or other users.
          <br />
          <br />
          Upon termination, your license to use the Service will immediately
          end. Provisions that by their nature should survive termination will
          remain in effect.
        </Paragraph>
      </InformationSection>
      <InformationSection title="14. Disclaimers" className="mt-20">
        <Paragraph>
          The Service is provided on an <TextBold>&quot;as is&quot;</TextBold>{" "}
          and <TextBold>&quot;as available&quot;</TextBold> basis. To the
          fullest extent permitted by law, LYNA disclaims all warranties,
          whether express or implied, including warranties of merchantability,
          fitness for a particular purpose, and non-infringement.
          <br />
          <br />
          We do not guarantee that the Service will be uninterrupted,
          error-free, or secure.
        </Paragraph>
      </InformationSection>
      <InformationSection title="15. Limitation of Liability" className="mt-20">
        <Paragraph>
          To the maximum extent permitted by law, LYNA shall not be liable for
          any indirect, incidental, special, or consequential damages.
        </Paragraph>
        <Paragraph>
          Our total liability arising out of or relating to the Service shall
          not exceed the greater of:
        </Paragraph>
        <Paragraph indent={"sm"} spacing={"none"}>
          • The amount you paid to LYNA in the 12 months preceding the claim, or
          <br />• <TextBold>£100.</TextBold>
        </Paragraph>
      </InformationSection>
      <InformationSection title="16. Indemnification" className="mt-20">
        <Paragraph>
          You agree to indemnify and hold harmless LYNA, its directors,
          officers, employees, and partners from any claims, liabilities,
          damages, or expenses arising out of your use of the Service, your User
          Content, or your breach of these Terms.
        </Paragraph>
      </InformationSection>
      <InformationSection
        title="17. Modifications to These Terms"
        className="mt-20"
      >
        <Paragraph>
          We may update these Terms from time to time. Material changes will be
          communicated via the Service, email, or other reasonable means.
          Continued use of the Service after changes become effective
          constitutes acceptance of the revised Terms.
        </Paragraph>
      </InformationSection>
      <InformationSection
        title="18. Governing Law and Jurisdiction"
        className="mt-20"
      >
        <Paragraph>
          These Terms are governed by and construed in accordance with the laws
          of <TextBold>England and Wales.</TextBold> Any disputes shall be
          subject to the exclusive jurisdiction of the courts of England and
          Wales, unless otherwise required by law.
        </Paragraph>
      </InformationSection>
      <InformationSection title="19. Severability" className="mt-20">
        <Paragraph>
          If any provision of these Terms is found to be invalid or
          unenforceable, the remaining provisions will remain in full force and
          effect.
        </Paragraph>
      </InformationSection>
      <InformationSection title="20. Contact Us" className="mt-20">
        <Paragraph>
          If you have any questions about these Terms, please contact us at:
          <br />
          Email: <TextBold>hello@lyna.com</TextBold>
        </Paragraph>
        <Paragraph className="mt-20">
          By using LYNA, you confirm that you have read, understood, and agree
          to these Terms of Use.
          <br />
          <br />
          <TextBold>Important Disclaimer:</TextBold> LYNA is not a substitute
          for professional healthcare advice. Always consult a qualified
          healthcare provider regarding any medical concerns.
        </Paragraph>
      </InformationSection>
    </InformationPage>
  );
};

export default TermsOfUse;
